<img align="left" src="https://lever-client-logos.s3.amazonaws.com/864372b1-534c-480e-acd5-9711f850815c-1524247202159.png" width=200>
<br></br>
<br></br>

# Neural Networks

## *Data Science Unit 4 Sprint 2 Assignment 1*

## Define the Following:
You can add image, diagrams, whatever you need to ensure that you understand the concepts below.

### Input Layer:
The input layer is the layer that actually takes in data. For example, it can take the brightness of a pixel in order when trying to classify images.
### Hidden Layer:
Hidden layers are nodes that we do not directly interact with. Generally, it will be a function that applies weights and biases to the nodes connected to it from the previous layer.
### Output Layer:
The output layer is where we read our answer.
### Neuron:
Neurons are nodes that store a function that takes in the previous layer and morphs it for use by the next layer of neurons.
### Weight:
The weighs are coefficients stat determine how much a given node from the previous layer effects the activation of a particular node.
### Activation Function:
Is a function that scales a value down to a number between 0 and 1
### Node Map:
The topology of a neural network
### Perceptron:
In machine learning, the perceptron is an algorithm for supervised learning of binary classifiers. A binary classifier is a function which can decide whether or not an input, represented by a vector of numbers, belongs to some specific class

## Inputs -> Outputs

### Explain the flow of information through a neural network from inputs to outputs. Be sure to include: inputs, weights, bias, and activation functions. How does it all flow from beginning to end?

Each layer after the input layer is connected to each node in the previous layer, and their activation is dependent on the activation of those previous layers. This is affected by weighsts, which determine how much a given node should affect this one, and a bias, which determines when it should matter. All this is then put into an activation function that smushes the functions down to between 0 and 1.

## Write your own perceptron code that can correctly classify (99.0% accuracy) a NAND gate. 

| x1 | x2 | y |
|----|----|---|
| 0  | 0  | 1 |
| 1  | 0  | 1 |
| 0  | 1  | 1 |
| 1  | 1  | 0 |

In [7]:
import pandas as pd
import numpy as np
np.random.seed(812)
data = { 'x1': [0,1,0,1],
         'x2': [0,0,1,1],
         'y':  [1,1,1,0]
       }

df = pd.DataFrame.from_dict(data).astype('int')

In [8]:
correct_outputs = df[['y']]
correct_outputs

y
0  1
1  1
2  1
3  0

In [9]:
##### Your Code Here #####

def sigmoid(x):
    return 1/(1+np.exp(-x))

def sigmoid_derivative(x):
    sx = sigmoid(x)
    return sx * (1-sx)



In [10]:
weights = np.random.random((3,1))
weights

array([[0.5049808 ],
       [0.60592761],
       [0.45748719]])

In [11]:
weighted_sum = np.dot(np.array(df), weights)
weighted_sum

array([[0.45748719],
       [0.96246799],
       [1.06341479],
       [1.11090841]])

In [12]:
activated_outputs = sigmoid(weighted_sum)
activated_outputs

array([[0.6124179 ],
       [0.72361567],
       [0.74334258],
       [0.75229843]])

In [13]:
error = correct_outputs - activated_outputs
correct_outputs

y
0  1
1  1
2  1
3  0

In [14]:
activated_outputs

array([[0.6124179 ],
       [0.72361567],
       [0.74334258],
       [0.75229843]])

In [15]:
error

y
0  0.387582
1  0.276384
2  0.256657
3 -0.752298

In [16]:
adjustments = error*sigmoid_derivative(weighted_sum)
adjustments

y
0  0.091997
1  0.055276
2  0.048966
3 -0.140187

In [17]:
weights = weights + np.dot(df.T, adjustments)
weights

array([[0.42006914],
       [0.51470641],
       [0.65372654]])

In [18]:
for iteration in range(10000):
    
    # Weighted sum of inputs / weights
    weighted_sum = np.dot(df, weights)
    
    # Activate!
    activated_output = sigmoid(weighted_sum)
    
    # Cac error
    error = correct_outputs - activated_output
    
    adjustments = error * sigmoid_derivative(weighted_sum)
    
    # Update the Weights
    weights = weights + np.dot(df.T, adjustments)
    
print("Weights after training")
print(weights)

print("Output after training")
print(activated_output)

Weights after training
[[-2.41044103]
 [-2.4100307 ]
 [ 7.49024349]]
Output after training
[[0.99944176]
 [0.99381701]
 [0.99381953]
 [0.0079989 ]]


## Implement your own Perceptron Class and use it to classify a binary dataset: 
- [The Pima Indians Diabetes dataset](https://raw.githubusercontent.com/ryanleeallred/datasets/master/diabetes.csv) 

You may need to search for other's implementations in order to get inspiration for your own. There are *lots* of perceptron implementations on the internet with varying levels of sophistication and complexity. Whatever your approach, make sure you understand **every** line of your implementation and what its purpose is.

In [4]:
diabetes = pd.read_csv('https://raw.githubusercontent.com/ryanleeallred/datasets/master/diabetes.csv')
diabetes.head()

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0            6      148             72             35        0  33.6   
1            1       85             66             29        0  26.6   
2            8      183             64              0        0  23.3   
3            1       89             66             23       94  28.1   
4            0      137             40             35      168  43.1   

   DiabetesPedigreeFunction  Age  Outcome  
0                     0.627   50        1  
1                     0.351   31        0  
2                     0.672   32        1  
3                     0.167   21        0  
4                     2.288   33        1

Although neural networks can handle non-normalized data, scaling or normalizing your data will improve your neural network's learning speed. Try to apply the sklearn `MinMaxScaler` or `Normalizer` to your diabetes dataset. 

In [10]:
from sklearn.preprocessing import MinMaxScaler, Normalizer

feats = list(diabetes)[:-1]

X = ...

In [ ]:
##### Update this Class #####

class Perceptron:
    
    def __init__(self, niter = 10):
        self.niter = niter
    
    def __sigmoid(self, x):
        return None
    
    def __sigmoid_derivative(self, x):
        return None

    def fit(self, X, y):
    """Fit training data
    X : Training vectors, X.shape : [#samples, #features]
    y : Target values, y.shape : [#samples]
    """

        # Randomly Initialize Weights
        weights = ...

        for i in range(self.niter):
            # Weighted sum of inputs / weights

            # Activate!

            # Cac error

            # Update the Weights


    def predict(self, X):
    """Return class label after unit step"""
        return None

In [207]:
class Perceptron:
    
    def __init__(self, iterations = 100, learning_rate = 0.01):
        self.iterations = iterations
        self.weights = None
        self.rate = learning_rate
        self.weighted_sum = None
        self.bias = None
        
    def __sigmoid(self, x):
        return 1/(1+np.exp(-x))

    def __sigmoid_derivative(self, x):
        sx = self.__sigmoid(x)
        return sx * (1-sx)
    
    def predict(self, X):
        self.weighted_sum = np.dot(X, self.weights) + self.bias
        activated_outputs = self.__sigmoid(self.weighted_sum)

        return activated_outputs
    
    def fit(self, X, y):
        self.weights = np.random.random(1 + X.shape[1]) 
        self.bias = np.array(np.random.random(1 + X.shape[1]))

        for _ in range(self.iterations):
            predictions = self.predict(X)

            error = y - predictions
    
            adjustments = error * self.__sigmoid_derivative(self.weighted_sum) * self.rate

            # Update the Weights
            print(X.shape)
            print(self.weights)
            print()
            print(X.T)
            print()
            print(adjustments.to_numpy())
            
            self.weights += np.dot(X.T, adjustments.to_numpy())
            weights
            # weights[0] = weights[0] + self.rate * error
            break
                

In [208]:
p = Perceptron()

In [209]:
df.shape[1] + 1

4

In [210]:
np.random.random( 4)

array([0.73356892, 0.78367609, 0.93038352, 0.42425562])

In [211]:
p.fit(df, df['y'])

ValueError: shapes (4,3) and (4,) not aligned: 3 (dim 1) != 4 (dim 0)

## Stretch Goals:

- Research "backpropagation" to learn how weights get updated in neural networks (tomorrow's lecture). 
- Implement a multi-layer perceptron. (for non-linearly separable classes)
- Try and implement your own backpropagation algorithm.
- What are the pros and cons of the different activation functions? How should you decide between them for the different layers of a neural network?