<img align="left" src="https://lever-client-logos.s3.amazonaws.com/864372b1-534c-480e-acd5-9711f850815c-1524247202159.png" width=200>
<br></br>
<br></br>

# Neural Networks

## *Data Science Unit 4 Sprint 2 Assignment 1*

## Define the Following:
You can add image, diagrams, whatever you need to ensure that you understand the concepts below.

### Input Layer:
The input layer is the layer that actually takes in data. For example, it can take the brightness of a pixel in order when trying to classify images.
### Hidden Layer:
Hidden layers are nodes that we do not directly interact with. Generally, it will be a function that applies weights and biases to the nodes connected to it from the previous layer.
### Output Layer:
The output layer is where we read our answer.
### Neuron:
Neurons are nodes that store a function that takes in the previous layer and morphs it for use by the next layer of neurons.
### Weight:
The weighs are coefficients stat determine how much a given node from the previous layer effects the activation of a particular node.
### Activation Function:
Is a function that scales a value down to a number between 0 and 1
### Node Map:
The topology of a neural network
### Perceptron:
In machine learning, the perceptron is an algorithm for supervised learning of binary classifiers. A binary classifier is a function which can decide whether or not an input, represented by a vector of numbers, belongs to some specific class

## Inputs -> Outputs

### Explain the flow of information through a neural network from inputs to outputs. Be sure to include: inputs, weights, bias, and activation functions. How does it all flow from beginning to end?

Each layer after the input layer is connected to each node in the previous layer, and their activation is dependent on the activation of those previous layers. This is affected by weighsts, which determine how much a given node should affect this one, and a bias, which determines when it should matter. All this is then put into an activation function that smushes the functions down to between 0 and 1.

## Write your own perceptron code that can correctly classify (99.0% accuracy) a NAND gate. 

| x1 | x2 | y |
|----|----|---|
| 0  | 0  | 1 |
| 1  | 0  | 1 |
| 0  | 1  | 1 |
| 1  | 1  | 0 |

In [1]:
import pandas as pd
import numpy as np
np.random.seed(812)
data = { 'x1': [0,1,0,1],
         'x2': [0,0,1,1],
         'y':  [1,1,1,0]
       }

df = pd.DataFrame.from_dict(data).astype('int')

In [2]:
correct_outputs = df[['y']]
correct_outputs

y
0  1
1  1
2  1
3  0

In [3]:
##### Your Code Here #####

def sigmoid(x):
    return 1/(1+np.exp(-x))

def sigmoid_derivative(x):
    sx = sigmoid(x)
    return sx * (1-sx)



In [4]:
weights = np.random.random((3,1))
weights

array([[0.5049808 ],
       [0.60592761],
       [0.45748719]])

In [5]:
weighted_sum = np.dot(np.array(df), weights)
weighted_sum

array([[0.45748719],
       [0.96246799],
       [1.06341479],
       [1.11090841]])

In [6]:
activated_outputs = sigmoid(weighted_sum)
activated_outputs

array([[0.6124179 ],
       [0.72361567],
       [0.74334258],
       [0.75229843]])

In [13]:
error = correct_outputs - activated_outputs
correct_outputs

y
0  1
1  1
2  1
3  0

In [14]:
activated_outputs

array([[0.6124179 ],
       [0.72361567],
       [0.74334258],
       [0.75229843]])

In [15]:
error

y
0  0.387582
1  0.276384
2  0.256657
3 -0.752298

In [16]:
adjustments = error*sigmoid_derivative(weighted_sum)
adjustments

y
0  0.091997
1  0.055276
2  0.048966
3 -0.140187

In [17]:
weights = weights + np.dot(df.T, adjustments)
weights

array([[0.42006914],
       [0.51470641],
       [0.65372654]])

In [18]:
for iteration in range(10000):
    
    # Weighted sum of inputs / weights
    weighted_sum = np.dot(df, weights)
    
    # Activate!
    activated_output = sigmoid(weighted_sum)
    
    # Cac error
    error = correct_outputs - activated_output
    
    adjustments = error * sigmoid_derivative(weighted_sum)
    
    # Update the Weights
    weights = weights + np.dot(df.T, adjustments)
    
print("Weights after training")
print(weights)

print("Output after training")
print(activated_output)

Weights after training
[[-2.41044103]
 [-2.4100307 ]
 [ 7.49024349]]
Output after training
[[0.99944176]
 [0.99381701]
 [0.99381953]
 [0.0079989 ]]


## Implement your own Perceptron Class and use it to classify a binary dataset: 
- [The Pima Indians Diabetes dataset](https://raw.githubusercontent.com/ryanleeallred/datasets/master/diabetes.csv) 

You may need to search for other's implementations in order to get inspiration for your own. There are *lots* of perceptron implementations on the internet with varying levels of sophistication and complexity. Whatever your approach, make sure you understand **every** line of your implementation and what its purpose is.

In [156]:
diabetes = pd.read_csv('https://raw.githubusercontent.com/ryanleeallred/datasets/master/diabetes.csv')
diabetes.head()

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0            6      148             72             35        0  33.6   
1            1       85             66             29        0  26.6   
2            8      183             64              0        0  23.3   
3            1       89             66             23       94  28.1   
4            0      137             40             35      168  43.1   

   DiabetesPedigreeFunction  Age  Outcome  
0                     0.627   50        1  
1                     0.351   31        0  
2                     0.672   32        1  
3                     0.167   21        0  
4                     2.288   33        1

In [158]:
list(diabetes)

['Pregnancies',
 'Glucose',
 'BloodPressure',
 'SkinThickness',
 'Insulin',
 'BMI',
 'DiabetesPedigreeFunction',
 'Age',
 'Outcome']

In [159]:
labels = diabetes["Outcome"]

In [160]:
diabetes = diabetes.drop("Outcome", axis=1)

In [161]:
diabetes.head()

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0            6      148             72             35        0  33.6   
1            1       85             66             29        0  26.6   
2            8      183             64              0        0  23.3   
3            1       89             66             23       94  28.1   
4            0      137             40             35      168  43.1   

   DiabetesPedigreeFunction  Age  
0                     0.627   50  
1                     0.351   31  
2                     0.672   32  
3                     0.167   21  
4                     2.288   33

Although neural networks can handle non-normalized data, scaling or normalizing your data will improve your neural network's learning speed. Try to apply the sklearn `MinMaxScaler` or `Normalizer` to your diabetes dataset. 

In [198]:
from sklearn.preprocessing import MinMaxScaler, Normalizer
from sklearn.model_selection import train_test_split


feats = list(diabetes)
scaler = MinMaxScaler()
scaled = pd.DataFrame(scaler.fit_transform(diabetes), columns = feats)

In [178]:
scaled

Pregnancies   Glucose  BloodPressure  SkinThickness   Insulin       BMI  \
0       0.352941  0.743719       0.590164       0.353535  0.000000  0.500745   
1       0.058824  0.427136       0.540984       0.292929  0.000000  0.396423   
2       0.470588  0.919598       0.524590       0.000000  0.000000  0.347243   
3       0.058824  0.447236       0.540984       0.232323  0.111111  0.418778   
4       0.000000  0.688442       0.327869       0.353535  0.198582  0.642325   
..           ...       ...            ...            ...       ...       ...   
763     0.588235  0.507538       0.622951       0.484848  0.212766  0.490313   
764     0.117647  0.613065       0.573770       0.272727  0.000000  0.548435   
765     0.294118  0.608040       0.590164       0.232323  0.132388  0.390462   
766     0.058824  0.633166       0.491803       0.000000  0.000000  0.448584   
767     0.058824  0.467337       0.573770       0.313131  0.000000  0.453055   

     DiabetesPedigreeFunction       Age  
0                    0.234415  0.483333  
1                    0.116567  0.166667  
2                    0.253629  0.183333  
3                    0.038002  0.000000  
4                    0.943638  0.200000  
..                        ...       ...  
763                  0.039710  0.700000  
764                  0.111870  0.100000  
765                  0.071307  0.150000  
766                  0.115713  0.433333  
767                  0.101196  0.033333  

[768 rows x 8 columns]

In [339]:
from sklearn.metrics import accuracy_score

class Perceptron:
    
    def __init__(self, iterations = 100, learning_rate = 0.01):
        self.iterations = iterations
        self.weights = None
        self.rate = learning_rate
        self.weighted_sum = None
        self.bias = None
        
    def __sigmoid(self, x):
        return 1/(1+np.exp(-x))

    def __sigmoid_derivative(self, x):
        sx = self.__sigmoid(x)
        return sx * (1-sx)
    
    def predict(self, X):
        self.weighted_sum = np.dot(X, self.weights)
        self.weighted_sum +=  self.bias
        activated_outputs = self.__sigmoid(self.weighted_sum)

        return activated_outputs
    
    def fit(self, X, y):
        self.weights = np.random.random( X.shape[1]) 
        self.bias = np.random.random(X.shape[1])

        for _ in range(self.iterations):
            predictions = self.predict(X)

            error = (y - predictions)**2
    
            adjustments = error * self.__sigmoid_derivative(self.weighted_sum) * self.rate

            # Update the Weights
            
            self.weights += np.dot(X.T, adjustments)
            self.bias += error * self.rate
            
            
    def score(self, X, y):
        results = self.predict(X)
        results = (results > 0.5).astype(int)
        print(results)
        return accuracy_score(results, y)
            
        
                

## Test with NAND

In [347]:
p = Perceptron(1000, 0.01)

In [348]:
p.fit(df, df['y'])

In [349]:
p.predict(df)

0    0.843106
1    0.886792
2    0.868176
3    0.999986
Name: y, dtype: float64

In [346]:
p.score(df, df['y'])

0    1
1    1
2    1
3    1
Name: y, dtype: int64


0.75

In [331]:
p = Perceptron(1000)

In [332]:
p.fit(scaled, labels)

In [333]:
p.predict(scaled)

0      0.904112
1      0.089374
2      0.912861
3      0.072760
4      0.921075
         ...   
763    0.113468
764    0.080094
765    0.089987
766    0.897410
767    0.078099
Name: Outcome, Length: 768, dtype: float64

In [334]:
p.score(scaled, labels)

0      1
1      0
2      1
3      0
4      1
      ..
763    0
764    0
765    0
766    1
767    0
Name: Outcome, Length: 768, dtype: int64


1.0

In [262]:
X_train, X_test, y_train, y_test = train_test_split(diabetes, labels, stratify=labels)

In [263]:
X_train

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
644            3      103             72             30      152  27.6   
438            1       97             70             15        0  18.2   
55             1       73             50             10        0  23.0   
305            2      120             76             37      105  39.7   
146            9       57             80             37        0  32.8   
..           ...      ...            ...            ...      ...   ...   
590           11      111             84             40        0  46.8   
101            1      151             60              0        0  26.1   
510           12       84             72             31        0  29.7   
547            4      131             68             21      166  33.1   
179            5      130             82              0        0  39.1   

     DiabetesPedigreeFunction  Age  
644                     0.730   27  
438                     0.147   21  
55                      0.248   21  
305                     0.215   29  
146                     0.096   41  
..                        ...  ...  
590                     0.925   45  
101                     0.179   22  
510                     0.297   46  
547                     0.160   28  
179                     0.956   37  

[576 rows x 8 columns]

In [335]:
from sklearn.pipeline import make_pipeline

classifier = make_pipeline(MinMaxScaler(), Perceptron(100, 0.1))

In [336]:
classifier.fit(X_train, y_train)

Pipeline(memory=None,
         steps=[('minmaxscaler', MinMaxScaler(copy=True, feature_range=(0, 1))),
                ('perceptron', <__main__.Perceptron object at 0x119769550>)],
         verbose=False)

In [337]:
classifier.score(X_train, y_train)

644    0
438    0
55     0
305    0
146    0
      ..
590    1
101    0
510    1
547    0
179    1
Name: Outcome, Length: 576, dtype: int64


1.0

In [338]:
classifier.score(X_test, y_test)

ValueError: operands could not be broadcast together with shapes (192,) (576,) (192,) 

## Stretch Goals:

- Research "backpropagation" to learn how weights get updated in neural networks (tomorrow's lecture). 
- Implement a multi-layer perceptron. (for non-linearly separable classes)
- Try and implement your own backpropagation algorithm.
- What are the pros and cons of the different activation functions? How should you decide between them for the different layers of a neural network?